{
    "name": "All In One Access Management, Audit Trail & Session Security",
    "version": "18.0.1.0.0",
    "category": "Extra Tools",
    "summary": "Complete governance suite to track active logins, audit system changes, "
               "and analyze user permissions via an Access Right Matrix",
    "author": "alzarough",
    'license': 'OPL-1',
    'price': 150.0,
    'currency': 'USD',
    "depends": ["base", "mail", "web"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/mail_template_data.xml",
        "data/ir_cron_data.xml",
        "views/user_session_search.xml",
        "views/user_session_views.xml",
        "views/audit_log_search.xml",
        "views/access_matrix_views.xml",
        "views/audit_log_views.xml",
        "views/audit_rule_views.xml",
        "data/audit_rule_data.xml",
        "views/dashboard_views.xml",
        "wizards/audit_export_wizard_views.xml",
        "wizards/access_matrix_export_wizard_views.xml",
        "views/res_config_settings_views.xml",
        "views/menu_views.xml",
    ],
    'images': [
        'static/description/banner.png',
        'static/description/banner.jpg',
        'static/description/icon.png',
    ],
    "assets": {
        "web.assets_backend": [
            "web/static/lib/Chart/Chart.js",
            "security_sentinel_360/static/src/js/audit_dashboard.js",
            "security_sentinel_360/static/src/xml/audit_dashboard.xml",
            "security_sentinel_360/static/src/scss/audit_dashboard.scss",
            "security_sentinel_360/static/src/js/access_matrix.js",
            'security_sentinel_360/static/src/xml/access_matrix.xml',
            'security_sentinel_360/static/src/scss/access_matrix.scss',
        ],
        'web.assets_frontend': [
            'security_sentinel_360/static/src/css/faq_accordion.css',
            'security_sentinel_360/static/src/js/faq_accordion.js',
        ],
    },
    "installable": True,
    "application": True,
}
